# Generated by Django 5.1.4 on 2024-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucaklar',
            name='aircraft',
            field=models.CharField(max_length=50),
        ),
    ]
